export const sp_text = {
ui:{
    categories: {
    cinema:'Cine Polaco',
    community:'Colectividad Polaca',
    contests:'Concursos',
    country:'Esto es Polonia',
    displays:'Exposiciones',
    news:'Actualidad',
    people:'Polacos en Mar del Plata',
    workshops:'Cursos y talleres',
    },
    contact: 'Contacto',
    admin_dashboard: 'PANEL DE ADMINISTRADOR',
    article_title: 'Título del artículo',
    article_date: 'Fecha',
    article_text: 'Texto',
    article_category: 'Categorías',
    article_image: 'Fotos',
    add_article: 'Agregar artículo',
    existing_articles: 'Artículos existentes',
    delete: 'borrar',
    see_more: 'ver más',
    see_less: 'ver menos',
    exit_prompt: '¿Esta seguro que quiere salir?',
    exit: 'salir',
    cancel: 'cancelar',
    expand: 'agrandar',
    gallery: 'Galería de imágenes',
    add_video: 'agregar video',
    added_videos: 'videos agregados',
    embed_video_title: 'instrucciones para agregar video',
    embed_video_text: "1-Hacer click en 'compartir' en el video que desea agregar.\n2-Hacer click en 'insertar'.\n3-Hacer click en 'copiar' en la esquina inferior derecha.\n4-Pegar lo copiar en el campo indicado como 'insertar iframe'", 
    text: 'Texto',
    article_images: 'Fotos de artículo',
    carousel: 'Carrusel',
    videos: 'Videos',
    references: 'Referencias',
    select: 'seleccionar',
    max_images: 'máxima cantidad de imágenes: ',
    layout_instructions_title: 'instrucciones para seleccionar formato',
    layout_instructions_text: "1-Seleccionar el formato deseado teniendo en cuenta las referencias por color.\n2-Si seleccionó el formato 1 o 2, seleccionar las imágenes que se desean mostrar contando las imagenes que seleccionó anteriormente en el campo FOTOS, por ejemplo, si seleccionó tres fotos y desea que la primera se parte del artículo, ingrese '1'.",
    layouts: 'formatos',
    article_added: 'Artículo agregado exitosamente.',
    article_deleted: 'Artículo eliminado exitosamente.',
    related_videos: 'Videos relacionados',
    no_more_articles: 'No hay más artículos para mostrar.',
}
}

const po_text = {
    
}